### ISSUE TITLE
Current page highlight in sidebar menu works only on localhost

### ISSUE THREAD

**Issue by RickCogley** [lumeland/theme-simple-wiki#19]
The automatic menu highlighting / expanding in the sidebar seems to work only on localhost. 

When I run the site on localhost, selecting a page makes its selection in the side menu be highlighted and visible, and it is "sticky" even if I refresh the page. However, after I publish, this does not work, and the menu remains collapsed. 

Here are two screenshots showing localhost and the published version. Both were tested on latest Edge and latest MacOS.

https://help.esolia.pro/en/security/deep-packet-inspection/

<img width="1605" alt="Screenshot 2024-10-16 at 17 18 12" src="https://github.com/user-attachments/assets/818c0a50-3958-44b9-a25f-844da123afe7">
<img width="1605" alt="Screenshot 2024-10-16 at 17 18 30" src="https://github.com/user-attachments/assets/1a0eb711-4c32-4cc6-bca8-312613f85a9a">

**Comment by oscarotero** [comment]
After inspecting your site, looks like the issue is for different cases.
The url in the menu is `https://help.esolia.pro/en/Security/deep-packet-inspection/` (Note the upper case `S` in `Security`) but the real url is `https://help.esolia.pro/en/security/deep-packet-inspection/`.

I need more investigation but generally it's good idea to have all urls in lowercase for cross compatibility

**Comment by RickCogley** [comment]
oh, wow, thanks. I'll fix them all to lowercase. I think this was when I was trying to make the sidebar menu look "normal" from a language perspective by capitalizing the words...
